import io
import os
import sys
from contextlib import asynccontextmanager
from pathlib import Path

import numpy as np
import torch
from fastapi import FastAPI, File, Form, HTTPException, Request, UploadFile
from fastapi.responses import HTMLResponse, JSONResponse, Response
from PIL import Image, UnidentifiedImageError


PROJECT_ROOT = Path(__file__).resolve().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from training.models.drunet import DRUNet  # noqa: E402


DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
DEFAULT_CKPT = PROJECT_ROOT / "checkpoints" / "DRUNET_DENOISER.pt"
MAX_UPLOAD_MB = int(os.getenv("MAX_UPLOAD_MB", "12"))


class DenoiserService:
    def __init__(self, checkpoint_path: Path, device: str):
        self.checkpoint_path = checkpoint_path
        self.device = device
        self.model = self._load_model()

    def _load_model(self) -> DRUNet:
        if not self.checkpoint_path.is_file():
            raise FileNotFoundError(f"Checkpoint not found: {self.checkpoint_path}")

        model = DRUNet().to(self.device)
        try:
            state = torch.load(self.checkpoint_path, map_location=self.device, weights_only=True)
        except TypeError:
            state = torch.load(self.checkpoint_path, map_location=self.device)

        if isinstance(state, dict) and "model_state_dict" in state:
            state = state["model_state_dict"]
        if isinstance(state, dict) and "state_dict" in state:
            state = state["state_dict"]

        cleaned = {}
        for key, value in state.items():
            cleaned[key[7:] if key.startswith("module.") else key] = value

        model.load_state_dict(cleaned, strict=True)
        model.eval()
        return model

    @staticmethod
    def estimate_sigma(img_rgb: np.ndarray) -> float:
        gray = 0.299 * img_rgb[:, :, 0] + 0.587 * img_rgb[:, :, 1] + 0.114 * img_rgb[:, :, 2]
        med = np.median(gray)
        mad = np.median(np.abs(gray - med))
        sigma = 1.4826 * mad
        return float(np.clip(sigma, 0.01, 0.25))

    @staticmethod
    def decode_image(image_bytes: bytes) -> np.ndarray:
        try:
            pil_image = Image.open(io.BytesIO(image_bytes)).convert("RGB")
        except UnidentifiedImageError as exc:
            raise ValueError("Uploaded file is not a valid image.") from exc
        return np.asarray(pil_image, dtype=np.float32) / 255.0

    @staticmethod
    def encode_png(img_rgb: np.ndarray) -> bytes:
        clipped = np.clip(img_rgb, 0.0, 1.0)
        image = Image.fromarray((clipped * 255.0).round().astype(np.uint8), mode="RGB")
        buffer = io.BytesIO()
        image.save(buffer, format="PNG")
        return buffer.getvalue()

    def denoise(self, image_bytes: bytes, sigma: float | None) -> tuple[bytes, float]:
        img = self.decode_image(image_bytes)
        sigma_value = float(np.clip(sigma, 0.0, 1.0)) if sigma is not None else self.estimate_sigma(img)

        tensor = torch.from_numpy(img).permute(2, 0, 1).unsqueeze(0).to(self.device)
        sigma_tensor = torch.tensor([[sigma_value]], dtype=tensor.dtype, device=tensor.device)

        with torch.inference_mode():
            output = self.model(tensor, sigma=sigma_tensor)
            output = torch.clamp(output, 0.0, 1.0)

        output_np = output.squeeze(0).permute(1, 2, 0).cpu().numpy()
        return self.encode_png(output_np), sigma_value


service: DenoiserService | None = None


@asynccontextmanager
async def lifespan(_: FastAPI):
    global service

    checkpoint_path = Path(os.getenv("CHECKPOINT_PATH", str(DEFAULT_CKPT))).resolve()
    service = DenoiserService(checkpoint_path=checkpoint_path, device=DEVICE)
    try:
        yield
    finally:
        service = None


app = FastAPI(
    title="DRUNet Denoiser API",
    description="Upload an image and receive a denoised PNG generated by the bundled DRUNet checkpoint.",
    version="1.0.0",
    lifespan=lifespan,
)


@app.get("/", response_class=HTMLResponse)
async def root() -> str:
    return """
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>DRUNet Denoiser</title>
    <style>
      :root {
        --bg: #f4efe8;
        --ink: #17130f;
        --muted: #645847;
        --accent: #1f8a70;
        --accent2: #ef7f4d;
        --card: rgba(255, 250, 243, 0.92);
        --line: rgba(23, 19, 15, 0.1);
      }
      * { box-sizing: border-box; }
      body {
        margin: 0;
        font-family: system-ui, sans-serif;
        color: var(--ink);
        background:
          radial-gradient(circle at top left, rgba(239, 127, 77, 0.20), transparent 30%),
          radial-gradient(circle at top right, rgba(31, 138, 112, 0.18), transparent 28%),
          linear-gradient(180deg, var(--bg), #e5d9c8);
      }
      main {
        max-width: 880px;
        margin: 0 auto;
        padding: 32px 20px 56px;
      }
      .card {
        background: var(--card);
        border: 1px solid var(--line);
        border-radius: 24px;
        padding: 24px;
        box-shadow: 0 20px 60px rgba(0, 0, 0, 0.08);
      }
      h1 {
        margin: 0 0 10px;
        font-size: clamp(2rem, 5vw, 3.4rem);
        line-height: 1;
      }
      p, li { color: var(--muted); line-height: 1.6; }
      code {
        background: rgba(0, 0, 0, 0.06);
        padding: 2px 6px;
        border-radius: 8px;
      }
      form {
        display: grid;
        gap: 14px;
        margin-top: 24px;
      }
      input, button {
        font: inherit;
      }
      input[type="file"], input[type="number"] {
        width: 100%;
        border: 1px solid var(--line);
        border-radius: 14px;
        padding: 12px 14px;
        background: white;
      }
      button {
        width: fit-content;
        border: 0;
        border-radius: 999px;
        background: linear-gradient(135deg, var(--accent), #236f8d);
        color: white;
        padding: 12px 18px;
        cursor: pointer;
        font-weight: 700;
      }
      .meta {
        display: flex;
        flex-wrap: wrap;
        gap: 10px;
        margin-top: 18px;
      }
      .pill {
        border: 1px solid var(--line);
        background: rgba(255,255,255,0.7);
        border-radius: 999px;
        padding: 8px 12px;
        color: var(--muted);
      }
    </style>
  </head>
  <body>
    <main>
      <section class="card">
        <h1>DRUNet Denoiser</h1>
        <p>This Hugging Face Space exposes a simple backend API for image denoising.</p>
        <div class="meta">
          <span class="pill">POST <code>/denoise</code></span>
          <span class="pill">GET <code>/health</code></span>
          <span class="pill">Swagger <code>/docs</code></span>
        </div>
        <form action="/denoise" method="post" enctype="multipart/form-data">
          <input type="file" name="image" accept="image/*" required />
          <input type="number" name="sigma" step="0.001" min="0" max="1" placeholder="Optional sigma in [0, 1]" />
          <button type="submit">Denoise Image</button>
        </form>
        <p>The response is a PNG image. Your Next.js frontend can post form-data with the file field named <code>image</code>.</p>
      </section>
    </main>
  </body>
</html>
"""


@app.get("/health")
async def health() -> JSONResponse:
    return JSONResponse(
        {
            "status": "ok",
            "device": DEVICE,
            "checkpoint": str(Path(os.getenv("CHECKPOINT_PATH", str(DEFAULT_CKPT))).resolve()),
            "model_loaded": service is not None,
        }
    )


@app.post("/denoise")
async def denoise(
    request: Request,
    image: UploadFile = File(...),
    sigma: str | None = Form(default=None),
) -> Response:
    if service is None:
        raise HTTPException(status_code=503, detail="Model is still loading. Please retry shortly.")

    image_bytes = await image.read()
    if not image_bytes:
        raise HTTPException(status_code=400, detail="Uploaded file is empty.")

    if len(image_bytes) > MAX_UPLOAD_MB * 1024 * 1024:
        raise HTTPException(status_code=413, detail=f"Image exceeds {MAX_UPLOAD_MB} MB upload limit.")

    sigma_value = sigma if sigma is not None else request.query_params.get("sigma")
    parsed_sigma: float | None = None
    if sigma_value not in (None, ""):
        try:
            parsed_sigma = float(sigma_value)
        except ValueError as exc:
            raise HTTPException(status_code=400, detail="Sigma must be a number in [0, 1].") from exc
        if not 0.0 <= parsed_sigma <= 1.0:
            raise HTTPException(status_code=400, detail="Sigma must be a number in [0, 1].")

    try:
        output_bytes, used_sigma = service.denoise(image_bytes=image_bytes, sigma=parsed_sigma)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Denoising failed: {exc}") from exc

    headers = {
        "x-denoise-sigma": f"{used_sigma:.6f}",
        "Content-Disposition": 'inline; filename="denoised-output.png"',
        "Cache-Control": "no-store",
    }
    return Response(content=output_bytes, media_type="image/png", headers=headers)
